### ISSUE TITLE
Can't run greasyfork locally

### ISSUE THREAD

**Issue by strongop** [JasonBarnabe/greasyfork#528]
Following this guide:
https://github.com/JasonBarnabe/greasyfork/wiki/Running-Greasy-Fork-locally

But https://greasyfork.org/data/ is empty, so the db is empty.
When the server runs, it seems unable to serve request since locales table is empty.

The console log is here:
```
user@linux:~/web/greasyfork$ rake ts:configure
Generating configuration to /home/user/web/greasyfork/config/development.sphinx.conf
user@linux:~/web/greasyfork$ rake ts:start
rake aborted!
ThinkingSphinx::SphinxAlreadyRunning: searchd is already running
/home/user/.rvm/gems/ruby-2.4.2/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/interfaces/daemon.rb:6:in `start'
/home/user/.rvm/gems/ruby-2.4.2/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/tasks.rb:65:in `block (2 levels) in <top (required)>'
/home/user/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => ts:start
(See full trace by running task with --trace)
user@linux:~/web/greasyfork$ bin/delayed_job start
delayed_job: process with pid 8061 started.
user@linux:~/web/greasyfork$ rails server
=> Booting WEBrick
=> Rails 5.1.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
[2018-02-10 18:06:37] INFO  WEBrick 1.3.1
[2018-02-10 18:06:37] INFO  ruby 2.4.2 (2017-09-14) [x86_64-linux]
[2018-02-10 18:06:37] INFO  WEBrick::HTTPServer#start: pid=8067 port=3000
Started GET "/" for ::1 at 2018-02-10 18:06:45 +0800
   (0.4ms)  SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
   (0.3ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
Processing by HomeController#index as HTML
  Locale Exists (0.3ms)  SELECT  1 AS one FROM `locales` WHERE `locales`.`code` = 'en-US' LIMIT 1
  Locale Exists (0.2ms)  SELECT  1 AS one FROM `locales` WHERE `locales`.`code` = 'en' LIMIT 1
  Locale Load (0.2ms)  SELECT `locales`.* FROM `locales` WHERE (code like 'en-%') ORDER BY `locales`.`ui_available` ASC, `locales`.`code` ASC
  CACHE Locale Exists (0.0ms)  SELECT  1 AS one FROM `locales` WHERE `locales`.`code` = 'en' LIMIT 1  [["code", "en"], ["LIMIT", 1]]
  CACHE Locale Load (0.0ms)  SELECT `locales`.* FROM `locales` WHERE (code like 'en-%') ORDER BY `locales`.`ui_available` ASC, `locales`.`code` ASC
  Locale Load (0.2ms)  SELECT  `locales`.* FROM `locales` WHERE `locales`.`code` = 'en' ORDER BY `locales`.`id` ASC LIMIT 1
Completed 401 Unauthorized in 21ms (ActiveRecord: 4.4ms)



NoMethodError - undefined method `code' for nil:NilClass:
  app/controllers/concerns/localized_request.rb:63:in `set_locale'

::1 - - [10/Feb/2018:18:06:45 HKT] "GET / HTTP/1.1" 500 99725
- -> /
Started POST "/__better_errors/60e1033be32bfb99/variables" for ::1 at 2018-02-10 18:06:46 +0800
::1 - - [10/Feb/2018:18:06:46 HKT] "POST /__better_errors/60e1033be32bfb99/variables HTTP/1.1" 200 41185
http://localhost:3000/ -> /__better_errors/60e1033be32bfb99/variables
::1 - - [10/Feb/2018:18:06:46 HKT] "GET /favicon.ico HTTP/1.1" 200 0
- -> /favicon.ico
Started GET "/" for ::1 at 2018-02-10 18:07:23 +0800
Processing by HomeController#index as HTML
  Locale Exists (0.3ms)  SELECT  1 AS one FROM `locales` WHERE `locales`.`code` = 'en-US' LIMIT 1
  Locale Exists (0.1ms)  SELECT  1 AS one FROM `locales` WHERE `locales`.`code` = 'en' LIMIT 1
  Locale Load (0.2ms)  SELECT `locales`.* FROM `locales` WHERE (code like 'en-%') ORDER BY `locales`.`ui_available` ASC, `locales`.`code` ASC
  CACHE Locale Exists (0.0ms)  SELECT  1 AS one FROM `locales` WHERE `locales`.`code` = 'en' LIMIT 1  [["code", "en"], ["LIMIT", 1]]
  CACHE Locale Load (0.0ms)  SELECT `locales`.* FROM `locales` WHERE (code like 'en-%') ORDER BY `locales`.`ui_available` ASC, `locales`.`code` ASC
  Locale Load (0.1ms)  SELECT  `locales`.* FROM `locales` WHERE `locales`.`code` = 'en' ORDER BY `locales`.`id` ASC LIMIT 1
Completed 401 Unauthorized in 5ms (ActiveRecord: 0.8ms)



NoMethodError - undefined method `code' for nil:NilClass:
  app/controllers/concerns/localized_request.rb:63:in `set_locale'

::1 - - [10/Feb/2018:18:07:23 HKT] "GET / HTTP/1.1" 500 99726
- -> /
Started POST "/__better_errors/f9c57c367457a08c/variables" for ::1 at 2018-02-10 18:07:23 +0800
::1 - - [10/Feb/2018:18:07:23 HKT] "POST /__better_errors/f9c57c367457a08c/variables HTTP/1.1" 200 41186
http://localhost:3000/ -> /__better_errors/f9c57c367457a08c/variables
Started GET "/" for ::1 at 2018-02-10 18:20:21 +0800
Processing by HomeController#index as HTML
  Locale Exists (0.3ms)  SELECT  1 AS one FROM `locales` WHERE `locales`.`code` = 'en-US' LIMIT 1
  Locale Exists (0.2ms)  SELECT  1 AS one FROM `locales` WHERE `locales`.`code` = 'en' LIMIT 1
  Locale Load (0.2ms)  SELECT `locales`.* FROM `locales` WHERE (code like 'en-%') ORDER BY `locales`.`ui_available` ASC, `locales`.`code` ASC
  CACHE Locale Exists (0.0ms)  SELECT  1 AS one FROM `locales` WHERE `locales`.`code` = 'en' LIMIT 1  [["code", "en"], ["LIMIT", 1]]
  CACHE Locale Load (0.0ms)  SELECT `locales`.* FROM `locales` WHERE (code like 'en-%') ORDER BY `locales`.`ui_available` ASC, `locales`.`code` ASC
  Locale Load (0.1ms)  SELECT  `locales`.* FROM `locales` WHERE `locales`.`code` = 'en' ORDER BY `locales`.`id` ASC LIMIT 1
Completed 401 Unauthorized in 5ms (ActiveRecord: 0.8ms)



NoMethodError - undefined method `code' for nil:NilClass:
  app/controllers/concerns/localized_request.rb:63:in `set_locale'

::1 - - [10/Feb/2018:18:20:21 HKT] "GET / HTTP/1.1" 500 99726
- -> /
Started POST "/__better_errors/52e6ec9b80ecd473/variables" for ::1 at 2018-02-10 18:20:21 +0800
::1 - - [10/Feb/2018:18:20:21 HKT] "POST /__better_errors/52e6ec9b80ecd473/variables HTTP/1.1" 200 41302
http://localhost:3000/ -> /__better_errors/52e6ec9b80ecd473/variables
Started GET "/" for ::1 at 2018-02-10 18:20:22 +0800
Processing by HomeController#index as HTML
  Locale Exists (0.2ms)  SELECT  1 AS one FROM `locales` WHERE `locales`.`code` = 'en-US' LIMIT 1
  Locale Exists (0.1ms)  SELECT  1 AS one FROM `locales` WHERE `locales`.`code` = 'en' LIMIT 1
  Locale Load (0.1ms)  SELECT `locales`.* FROM `locales` WHERE (code like 'en-%') ORDER BY `locales`.`ui_available` ASC, `locales`.`code` ASC
  CACHE Locale Exists (0.0ms)  SELECT  1 AS one FROM `locales` WHERE `locales`.`code` = 'en' LIMIT 1  [["code", "en"], ["LIMIT", 1]]
  CACHE Locale Load (0.0ms)  SELECT `locales`.* FROM `locales` WHERE (code like 'en-%') ORDER BY `locales`.`ui_available` ASC, `locales`.`code` ASC
  Locale Load (0.1ms)  SELECT  `locales`.* FROM `locales` WHERE `locales`.`code` = 'en' ORDER BY `locales`.`id` ASC LIMIT 1
Completed 401 Unauthorized in 4ms (ActiveRecord: 0.6ms)



NoMethodError - undefined method `code' for nil:NilClass:
  app/controllers/concerns/localized_request.rb:63:in `set_locale'

::1 - - [10/Feb/2018:18:20:22 HKT] "GET / HTTP/1.1" 500 99726
- -> /
Started POST "/__better_errors/6a683f6031192568/variables" for ::1 at 2018-02-10 18:20:22 +0800
::1 - - [10/Feb/2018:18:20:22 HKT] "POST /__better_errors/6a683f6031192568/variables HTTP/1.1" 200 41297
http://localhost:3000/ -> /__better_errors/6a683f6031192568/variables


```

**Comment by strongop** [comment]
Error show on page:
![screenshot-2018-2-10 nomethoderror at](https://user-images.githubusercontent.com/35924000/36061850-a5df0532-0e9b-11e8-934e-b3f57d9ef5d7.png)

**Comment by JasonBarnabe** [comment]
I have regenerated the file in https://greasyfork.org/data/

**Comment by strongop** [comment]
Thanks!
This time goes further.

When I try to view the info a of a script, I got the following error, looks like caused by no record in **site_applications** table.
```
Started GET "/en/scripts/37974-12306%E5%B8%A6%E6%88%91%E5%9D%90%E7%81%AB%E8%BD%A6%E5%9B%9E%E5%AE%B6" for ::1 at 2018-02-13 21:45:50 +0800
Processing by ScriptsController#show as HTML
  Parameters: {"locale"=>"en", "id"=>"37974-12306带我坐火车回家"}
  Script Load (0.2ms)  SELECT  `scripts`.* FROM `scripts` WHERE `scripts`.`id` = 37974 LIMIT 1
  Script Load (0.2ms)  SELECT  `scripts`.* FROM `scripts` WHERE `scripts`.`id` = 37974 LIMIT 1
  User Load (0.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 165635
  LocalizedScriptAttribute Load (0.2ms)  SELECT `localized_script_attributes`.* FROM `localized_script_attributes` WHERE `localized_script_attributes`.`script_id` = 37974
  Locale Load (0.1ms)  SELECT `locales`.* FROM `locales` WHERE `locales`.`id` = 187
  Compatibility Load (0.1ms)  SELECT `compatibilities`.* FROM `compatibilities` WHERE `compatibilities`.`script_id` = 37974
  ScriptVersion Load (0.1ms)  SELECT `script_versions`.* FROM `script_versions` WHERE `script_versions`.`script_id` = 37974
Cache miss - scripts/get_by_sitesgreasyfork - {}
Loading by_sites
   (0.2ms)  				SELECT
					text, SUM(daily_installs) install_count, COUNT(s.id) script_count
				FROM script_applies_tos
				JOIN scripts s ON script_id = s.id
				JOIN site_applications on site_applications.id = site_application_id
				WHERE
					domain
					AND script_type_id = 1
					AND script_delete_type_id IS NULL
					AND !tld_extra
					AND `sensitive` = false
				GROUP BY text
				ORDER BY text

Loading all_sites
   (0.1ms)  			SELECT
				sum(daily_installs) install_count, count(distinct scripts.id) script_count
			FROM scripts
			WHERE
				script_type_id = 1
				AND script_delete_type_id is null
				AND NOT EXISTS (SELECT * FROM script_applies_tos WHERE script_id = scripts.id)

Combining by_sites and all_sites
Cache stored - scripts/get_by_sitesgreasyfork - {}
  Rendering scripts/show.html.erb within layouts/scripts
  Rendered scripts/_install_button.html.erb (0.9ms)
  Script Load (10.7ms)  SELECT `scripts`.* FROM `scripts` WHERE `scripts`.`promoted` = 1
  Rendered scripts/_install.html.erb (14.4ms)
  Rendered scripts/_feedback_suggestion.html.erb (1.4ms)
  Rendered scripts/_ratings.html.erb (0.4ms)
  ScriptAppliesTo Exists (0.2ms)  SELECT  1 AS one FROM `script_applies_tos` WHERE `script_applies_tos`.`script_id` = 37974 LIMIT 1
  ScriptAppliesTo Load (0.2ms)  SELECT `script_applies_tos`.* FROM `script_applies_tos` WHERE `script_applies_tos`.`script_id` = 37974
  SiteApplication Load (0.1ms)  SELECT  `site_applications`.* FROM `site_applications` WHERE `site_applications`.`id` = 11244 LIMIT 1
  Rendered scripts/show.html.erb within layouts/scripts (25.1ms)
Completed 401 Unauthorized in 36ms (ActiveRecord: 12.6ms)



Module::DelegationError - ScriptAppliesTo#domain delegated to site_application.domain, 
but site_application is nil: #<ScriptAppliesTo id: 585446, script_id: 37974, site_application_id: 11244, tld_extra: false>:
  app/models/script_applies_to.rb:5:in `rescue in domain'
  app/models/script_applies_to.rb:5:in `domain'
  app/helpers/scripts_helper.rb:33:in `block in script_applies_to_list_contents'
  app/helpers/scripts_helper.rb:33:in `script_applies_to_list_contents'
  app/views/scripts/show.html.erb:104:in `_app_views_scripts_show_html_erb__2568011834265894733_70108879175600'

::1 - - [13/Feb/2018:21:45:50 HKT] "GET /en/scripts/37974-12306%E5%B8%A6%E6%88%91%E5%9D%90%E7%81%AB%E8%BD%A6%E5%9B%9E%E5%AE%B6 HTTP/1.1" 500 130517
- -> /en/scripts/37974-12306%E5%B8%A6%E6%88%91%E5%9D%90%E7%81%AB%E8%BD%A6%E5%9B%9E%E5%AE%B6
Started POST "/__better_errors/4a22695dcbd772f2/variables" for ::1 at 2018-02-13 21:45:50 +0800
  SiteApplication Load (0.2ms)  SELECT  `site_applications`.* FROM `site_applications` WHERE `site_applications`.`id` = 11244 LIMIT 11
::1 - - [13/Feb/2018:21:45:50 HKT] "POST /__better_errors/4a22695dcbd772f2/variables HTTP/1.1" 200 39325
http://localhost:3000/en/scripts/37974-12306%E5%B8%A6%E6%88%91%E5%9D%90%E7%81%AB%E8%BD%A6%E5%9B%9E%E5%AE%B6 -> /__better_errors/4a22695dcbd772f2/variables
Started POST "/__better_errors/4a22695dcbd772f2/eval" for ::1 at 2018-02-13 22:14:23 +0800
::1 - - [13/Feb/2018:22:14:23 HKT] "POST /__better_errors/4a22695dcbd772f2/eval HTTP/1.1" 200 120
http://localhost:3000/en/scripts/37974-12306%E5%B8%A6%E6%88%91%E5%9D%90%E7%81%AB%E8%BD%A6%E5%9B%9E%E5%AE%B6 -> /__better_errors/4a22695dcbd772f2/eval

```

**Comment by strongop** [comment]
```mysql
MariaDB [greasyfork]> select * from site_applications;
Empty set (0.00 sec)

MariaDB [greasyfork]> desc site_applications;
+--------+------------+------+-----+---------+----------------+
| Field  | Type       | Null | Key | Default | Extra          |
+--------+------------+------+-----+---------+----------------+
| id     | bigint(20) | NO   | PRI | NULL    | auto_increment |
| text   | text       | NO   |     | NULL    |                |
| domain | tinyint(1) | NO   |     | NULL    |                |
+--------+------------+------+-----+---------+----------------+
3 rows in set (0.00 sec)


```

**Comment by strongop** [comment]
I think table `site_applications` is migrated from `script_applies_tos` by 20171014004054_add_domains.rb

**Comment by JasonBarnabe** [comment]
You are correct. I must whitelist the tables to be included, and that was not added. I have added it now, let me know if there are further issues.

**Comment by strongop** [comment]
Thanks!
Everything works fine now, except the search function.
Which is caused by no sphinx index.
After run the following command, search works too.
`indexer -c config/development.sphinx.conf --all - build sphinx index`

```shell
xb@xb:~/web/greasyfork$ rake ts:start
Sphinx 2.2.11-id64-release (95ae9a6)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/home/xb/web/greasyfork/config/development.sphinx.conf'...
listening on 127.0.0.1:9306
precaching index 'script_core'
WARNING: index 'script_core': preload: failed to open /home/xb/web/greasyfork/db/sphinx/development/script_core.sph: No such file or directory; NOT SERVING
precaching index 'script_delta'
WARNING: index 'script_delta': preload: failed to open /home/xb/web/greasyfork/db/sphinx/development/script_delta.sph: No such file or directory; NOT SERVING
precached 2 indexes in 0.000 sec
Started searchd successfully (pid: 7825).
xb@xb:~/web/greasyfork$ ls db/sphinx/development/
xb@xb:~/web/greasyfork$ rails server
```

**Comment by strongop** [comment]
BTW, I want to say, maybe XZ is a better choice for compress the database, which will result in less traffic on server.

See my experiment below, on an 8 Core Machine:

---
1. xz with default compress ratio, compessed file size: 116.6MB
Memory Used During compress: 1GiB
```shell
$ xz --keep --compress --stdout --threads=$(cat /proc/cpuinfo|grep '^processor' | wc -l) --verbose data >db--default.sql.xz
data (1/1)
  100 %     116.6 MiB / 1,965.0 MiB = 0.059    21 MiB/s       1:34             
```

2. xz with best compress ratio, compessed file size: 70.2MB
Memory Used During compress: **7GiB**
```shell
$ xz --keep --compress --stdout --threads=$(cat /proc/cpuinfo|grep '^processor' | wc -l) --best --verbose data >db--best.sql.xz
data (1/1)
  100 %      70.2 MiB / 1,965.0 MiB = 0.036    15 MiB/s       2:13             
```

3. gzip with default compress rate, compessed file size: 418MB
Memory Used During compress: very little
```shell
$ gzip --keep --stdout --verbose data >db--default.sql.gz`
$ ls -lh
-rw-r--r-- 1 xiaobai xiaobai 418M Feb 14 17:04 db--default.sql.gz
```

**Comment by JasonBarnabe** [comment]
The memory usage would be problematic, but I'll keep that in mind.

**Comment by moham96** [comment]
I have the same issue with the "NoMethodError - undefined method `code' for nil:NilClass:" if I use the structure.sql since it has empty locales table.
and https://greasyfork.org/data/ is empty for me too

**Comment by JasonBarnabe** [comment]
I have generated the public dump in https://greasyfork.org/data/
